version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.3"
ports: "80:80"

packages: [php-imagick, php-simplexml, imagemagick, ghostscript, poppler-utils]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "npm update"


  run:


  dev:
    - "sudo phpdismod xdebug"
    - "sudo service apache2 restart"

  test:


