// Autogenerated file by brace/mod-router - do not change manually!
export const ROUTE_PREFIX = "%%ROUTE_PREFIX%%";
export const API = {
	"api.upload_POST": "POST@/v1/api/{subscription_id}/{scope_id}/upload"
};